### ISSUE TITLE
Comms v3 Release

### ISSUE THREAD

**Issue by hugoArregui** [decentraland/comms-v3#28]
- [x] Sync with WeMeta team
- [x] Implement /lambdas/hot-scenes and lambdas/realms for v3
- [x] ADR
- [x] Add new endpoints to API spec
- [x] peer count per parcel /stats/parcel - for v2 for DG
- [x] peer count per parcel /stats/parcel - for v3
- [x] /about
  - [x] add realm name 
  - [x] add service version 
  - [x] add bff.userCount
  - [x] hash for content
  - [x] hash for lambda
  - [x] move comms protocol inside comms
- [x] update catalyst-monitor
- [x] update catalyst-owner for v2
- [x] update catalyst-owner for v3
- [x] load balancer using /about
- [x] support for max peers for explorer realm selection
  - [x] Kernel: user /about for realm selection
- [x] implement /comms/* for v3
