### ISSUE TITLE
Comms tracking

### ISSUE THREAD

**Issue by hugoArregui** [decentraland/comms-v3#45]
# Pending tasks
- [x] Configure .today BFF pointing to non-working mini-comms
- [x] Configure .org mini-comms for .org BFF
- [ ] https://github.com/decentraland/cli/pull/842 (CLI) (WIP) 
  - [ ] Run performance tests in Kernel profiling with Unity Editor
  - [ ] https://github.com/decentraland/kernel/pull/535
    - [ ] Finish documentation and update RFC4 and RFC5, mark them as accepted
- [x] Update Kernel comms protocol to match RFC-4: remove date from transport and add it to chat messages. So kernel should use position index for example, instead of the timestamp.
- [x] Change the simulation to include some weareables in the profile
- [x] Review websocket comms crashes (v3 and mini comms)
- [ ] Run an internal playtest to validate the conditions listed in https://github.com/decentraland/kernel/pull/535
- [ ] Refactor lambdas/poi code to wait for next BFF
- [x] Document `/about` endpoint semantics, create ADR, link in RFC-2

# Test environments
- [ ] `/changerealm https://explorer-bff.decentraland.zone` working mini-comms and goerli catalyst
- [ ] `/changerealm https://explorer-bff.decentraland.org` working mini-comms and mainnet catalyst
- [ ] `/changerealm https://explorer-bff.decentraland.zone` non-working mini-comms and mainnet catalyst
- [ ] `/changerealm https://peer.decentraland.org` comms v2 and mainnet catalyst

# Deferred tasks
- [x] Unify mini-comms with ws-room-service 

# Log
- 26/9 @menduz created a simulation with 100 peers all kernel side, the performance was great, this hints to a problem in the ws transport itself or that we need more complex profiles, like wearables
- 27/9 @hugoArregui added protobuffer encoding/decoding to the simulation making it more realistic, but the results were the same, protobuffer doesn't seems to be the problem
- 27/9 @hugoArregui create a simulation with 100 peers in WS, the performance was great as well, so this hints there is no problem in the transport itself 
- 27/9 @hugoArregui create a simulation with 20 peers in WS using wearables, it worked well. This was tested in .zone
- 28/9 @hugoArregui create a simulation with 20 peers in WS using wearables, it worked well. This was tested in .org, but it's trying to resolve the content/lambdas url using the bff domain, instead of the publicUrl defined in /about, I need to fix this first
- 28/9 @hugoArregui and @menduz tested v3 with ws-room-service in peer-ec2, using bots
  - [ ] @hugoArregui had a disconnection with `https://play.decentraland.org/?disconnection-reason=logged-in-somewhere-else`
  - [ ] @menduz refreshed the page and got assign to a p2p island 
  - [x] the server was fine, but review this error:
  
  ```
  2022-09-28T16:31:50.969Z [ERROR] (RoomsComponent): Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writevGeneric (node:internal/stream_base_commons:143:3)
    at Socket._writeGeneric (node:net:872:11)
    at Socket._writev (node:net:881:8)
    at doWrite (node:internal/streams/writable:408:12)
    at clearBuffer (node:internal/streams/writable:563:5)
    at Socket.Writable.uncork (node:internal/streams/writable:350:7)
    at Sender.sendFrame (/app/node_modules/ws/lib/sender.js:471:20)
    at Sender.send (/app/node_modules/ws/lib/sender.js:359:12)
    at WebSocket.send (/app/node_modules/ws/lib/websocket.js:468:18)	{"errno":-32,"code":"EPIPE","syscall":"write"}
    
    ```
