### ISSUE TITLE
P2P Adapter

### ISSUE THREAD

**Issue by pentreathm** [decentraland/comms-v3#47]
PoC for ADR-114 https://github.com/decentraland/adr/pull/111 

Development Tasks 
- [x] P2P Kernel Protocol (each pear listens to the mesh and manages the routing) https://github.com/decentraland/kernel/pull/667
- [x] BOTs tooling to stress comms for this PoC
- [x] Connection to the BFF using the micro-web-socket 
- [x] PING support to generate load and get some metrics 
- [x] Implement the Messaging Service as part of the PoC 
- [x] Stress test P2P, get the MAX optimum number for an island size (0 to 100) 
- [x] Performance improvements based on the stress tests results (message size)
- [x] Create a metrics board to visualize comms performance 
- [ ] Adapt the P2P solution to BFF and Kernel
- [ ] Integrate solution with a Catalyst & Kernel in Zone 
- [ ] P2P Play Tests 

- [ ] Rollout

Risks 
- The solution doesn't scale as expected: mesh updates take too long to arrive then routes are outdated, packet loss, messages are too big, voice chat experience cuts or the nearby chat gets messy  
- A worse performance than Comms v2 
- Problems in dependencies

**Comment by hugoArregui** [comment]
Closing this issue because we are going to postpone P2P indefinitely
