### ISSUE TITLE
Comms over LiveKit 

### ISSUE THREAD

**Issue by pentreathm** [decentraland/comms-v3#48]
PoC: Have a single Catalyst running comms over LiveKit and test if the voice chat is performant when having up to 100 users connected 

Development 
- [x] LiveKit metrics in Grafana 
- [x] Stress tests 
- [x] Compare PING performance with P2P. Expected: worse performance than P2P in small islands and better and consistent performance when the island grows  
- [x] Test with users 
- [ ] LiveKit Cloud cost analysis 

Alternatives after the cost analysis: 
- Centralize the communications and cover the LiveKit Cloud cost and decentralize the governance of the service by asking the DAO to manage this service. 
- Design a hosted LivKit solution that can scale for the Catalyst Owners
